version: "3.8"

services:
  oracledb:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: oracledb
    environment:
      - ORACLE_PWD=root123@@__
      - ORACLE_SID=MYTASK
    ports:
      - "1521:1521"
      - "5500:5500"
    networks:
      - app-network
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup

  java-app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - oracledb
    environment:
      - DB_PASSWORD=root123@@__
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  oracle-data:
  oracle-backup: