version: '3.8'

services:
  oracledb:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: oracledb
    environment:
      - ORACLE_PWD=root123
      - ORACLE_SID=MYTASK
    networks:
      - app-network
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup

  java-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - oracledb
    environment:
      - DB_PASSWORD=root123
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  oracle-data:
  oracle-backup: