version: '3.8'

services:
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - "1521:1521"
    environment:
      ORACLE_ALLOW_REMOTE: "true"
      ORACLE_DISABLE_ASYNCH_IO: "true"
    volumes:
      - oracle-data:/u01/app/oracle

  java-app:
    context: ./
    dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db

volumes:
  oracle-data: