spring:
  datasource:
    url: "jdbc:oracle:thin:@oracledb:1521:MYTASK"
    username: "system"
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect